In [30]:
# 'jupyter notebook' is the terminal command to launch Jupyter Notebooks
import pandas as pd

# NOTE: This is the value from the GitHub Codespaces 'vigilant yodel' python environment instance

In [31]:
# Q1. Pandas version
# What version of Pandas did you install?
print(f"ANSWER: \r\n  Pandas version: {pd.__version__}")

# Answer is 3.0.5

# NOTE: This is the value from the GitHub Codespaces 'vigilant yodel' python environment instance

ANSWER: 
  Pandas version: 3.0.5


In [32]:
# Q1. Read data into a pandas dataframe
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [33]:
# BONUS: Preview dataset
print(f"VALIDATION: \r\n{df.head()}")

VALIDATION: 
   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4   
1        2008  Europe    Diesel  Front-wheel drive          4   
2        1996    Asia  Gasoline  Front-wheel drive          5   
3        1989  Europe  Gasoline  Front-wheel drive          4   
4        1994     USA    Diesel  Front-wheel drive          3   

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2180              6       243.0            3870   
1                 2390              6       272.0            4210   
2                 2320              6       267.0            4240   
3                 2130              6       258.0            4490   
4                 2580              7       304.0            4510   

   acceleration  fuel_efficiency_mpg  
0           NaN                 31.9  
1           NaN                 31.3  
2          17.3                 27.5  
3          18.7          

In [34]:
# Q2. Records count
# How many records are in the dataset?
#     5000
#     9000
#     10000
#     15000

# count the number of rows in the dataframe
#   approach 1: 
#     1. Think of the dataframe as a list (list A) of lists Lists B...Z)
#     2. Counting the number of elements in list A will return the answer
print(f"ANSWER: \r\n  APPROACH 1: Count of rows using the list object len() method: {len(df)} \r\n")

# inspect the dataframe and select the appropriate size dimention
#     1. shape is an attribute 
#     2. shape is not a method; it does not support parenthesis as they are used to hold method parameters)
#     3. pandas dataframes are strictly 2-dimentional structures
#          The first size element is the row count
#          The second size element is the column count
print(f"ANSWER: \r\n  APPROACH 2: Count of rows using the shape attribute: {df.shape[0]} \r\n")

# manually confirm result by reviewing a count of all populated rows for every column in the dataframe
print(f"VALIDATION:    Manually reviewing a count of all populated cells by column: \r\n {df.count()} \r\n")

# Answer is 10000 and the result of a manual inspection of the 

ANSWER: 
  APPROACH 1: Count of rows using the list object len() method: 10000 

ANSWER: 
  APPROACH 2: Count of rows using the shape attribute: 10000 

VALIDATION:    Manually reviewing a count of all populated cells by column: 
 model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64 



In [35]:
# Q3. Fuel types
# How many fuel types are presented in the dataset?
#     1
#     2
#     3
#     4

# create a new dataframe to create a row for each 'fuel_type' with a row number and a count of records by fuel_type
counts = (
    df.groupby("fuel_type")        # Group By 'fuel_type'
      .size()                      # Count the number of rows in each fuel_type group
      .reset_index(name="count")   # Convert the grouped result back into a DataFrame
                                   #   and name the count column "count"
)

# Add a "row_number" column 
counts.insert(
    0,                             # insert column at position zero
    "row_number",                  # name the column 'row_number'
    range(1, len(counts) + 1)      # populate column with a range function 
                                   #   (increase start and end index positions by one)
)

# Return a count of rows ressulting after .groupby()
print(f"ANSWER: \r\n  count of fuel_types: {len(counts)}\r\n")

print(f"VALIDATION: \r\n  review aggregated results and manually count rows: \r\n  {counts}")

# Answer: 3

ANSWER: 
  count of fuel_types: 3

VALIDATION: 
  review aggregated results and manually count rows: 
     row_number fuel_type  count
0           1    Diesel   2053
1           2  Gasoline   6913
2           3    Hybrid   1034


In [36]:
# Q4. Missing values
# How many columns in the dataset have missing values?
#     0
#     1
#     2
#     3
#     4

# Number of columns containing at least one missing value
missing_column_count = df.isna().any(axis=0).sum()
#                      df.isna()      searches dataframe df for missing values 
#                                      'true' means missing values found and 
#                                      'false' means missing values not found
#                        .any(axis=0) .any checks the column to see if any row
#                                       contains a 'true'
#                                     axis=0 (default) means to check by df columns
#                                     axis=1 means to check by df rows
#                        .sum()       counts the columns where .any() is 'true'
print(f"ANSWER: \r\n        count of columns with missing values:\r\n        {missing_column_count} \r\n")

columns_with_missing = df.columns[df.isna().any()]
#                      df.columns     returns column label within a pandas dataframe
#                        df.isna()    searches dataframe df for missing values 
#                                       'true' means missing values found and 
#                                       'false' means missing values not found
#                        .any()       checks each column for at least one 'true'
#                                       axis=0 (default) means to check by df columns
#                                       axis=1 means to check by df rows      
print(f"BONUS: \r\n        labels for columns with missing values: \r\n {columns_with_missing} \r\n")


print(f"VALIDATION: \r\n(Count of rows with values by column) \r\n{df.count()} \r\n")    # count number of rows containing values for all columns

#Answer is 2

ANSWER: 
        count of columns with missing values:
        2 

BONUS: 
        labels for columns with missing values: 
 Index(['horsepower', 'acceleration'], dtype='str') 

VALIDATION: 
(Count of rows with values by column) 
model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64 



In [37]:
# Q5. Max fuel efficiency
# What's the maximum fuel efficiency of cars from Asia?
#     21.2
#     31.2
#     41.2
#     51.2

print(f"ANSWER: \r\n  Maximum fuel efficiency:  {df['fuel_efficiency_mpg'].max()}")    # Select the maximum value in the 'fuel_efficiency_mpg' column

# Answer is 41.2

ANSWER: 
  Maximum fuel efficiency:  41.2


In [38]:
# Q6.1 Median value of horsepower
#     Q6.1 Find the median value of the horsepower column in the dataset.
#     Q6.2 Next, calculate the most frequent value of the same horsepower column.
#     Q6.3 Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
#     Q6.4 Now, calculate the median value of horsepower once again.
# 
# Has it changed?
#     Yes, it increased
#     Yes, it decreased
#     No

In [39]:
# Q6.1 Find the median value of the horsepower column in the dataset.)
print(f"ANSWER: \r\n  Median horsepower:  {df['horsepower'].median()}")

ANSWER: 
  Median horsepower:  254.0


In [40]:
# Q6.2 Next, calculate the most frequent value of the same horsepower column.
print('Q6.2 Next, calculate the most frequent value of the same horsepower column.')
print(f"ANSWER: \r\n  Most frequent horsepower value:  {df['horsepower'].mode()} ")  # Select the most frequently occuring value in the 'horsepower' column


Q6.2 Next, calculate the most frequent value of the same horsepower column.
ANSWER: 
  Most frequent horsepower value:  0    252.0
Name: horsepower, dtype: float64 


In [41]:
# Q6.3 Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
print('df_Q6_3')

# create a copy of the dataframe
df_Q6_3 = df  

# replace the contents of the 'horsepower' column 
df_Q6_3["horsepower"] = df['horsepower'].fillna(df['horsepower'].median())   

# explanation of chained methods
                    # 1. df['horsepower']              Select the 'horsepower' column in dataframe 'df'
                    # 2.   .fillna                     Find NA (missing) values in column 'horsepower;
                    # 3.   df['horsepower'].median()   Replace NA (missing) values with the calculated median of the 'horsepower' column


df_Q6_3


In [42]:
# Q6.3.1 Verify that Q6.3 worked
df_Q3_1 = df.count()
print(f"VERIFICATION: \r\n{df_Q3_1}")

VERIFICATION: 
model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower             10000
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64


In [43]:
# Q7. Sum of weights
#
#    Q7.1 Select all the cars from Asia
#    Q7.2 Select only columns vehicle_weight and model_year
#    Q7.3 Select the first 7 values
#    Q7.4 Get the underlying NumPy array. Let's call it X.
#    Q7.5 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#    Q7.6 Invert XTX.
#    Q7.7 Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
#    Q7.8 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#    Q7.9 What's the sum of all the elements of the result?
#
#    Note: You just implemented linear regression. We'll talk about it in the next lesson.
#
#    0.0369
#    0.369
#    3.69
#    36.9


In [44]:
# Q7.1 Select all the cars from Asia
df_Q7_1 = df.query('origin == "Asia"')

In [45]:
# Q7.1 Verify that Q6.3 worked
# print(df_Q7_1.count())
print(f"VERIFICATION: \r\n  Count of records where 'origin' == 'Asia' by using the shape attribute: {df_Q7_1.shape[0]} \r\n")

VERIFICATION: 
  Count of records where 'origin' == 'Asia' by using the shape attribute: 2994 



In [46]:
# Q7.2 Select only columns vehicle_weight and model_year
df_Q7_2 = df[['vehicle_weight','model_year']]
    
print(f"VERIFICATION: \r\n{df_Q7_2}")


VERIFICATION: 
      vehicle_weight  model_year
0               3870        2006
1               4210        2008
2               4240        1996
3               4490        1989
4               4510        1994
...              ...         ...
9995            4690        2005
9996            4370        1993
9997            4590        2014
9998            4450        2004
9999            4370        2011

[10000 rows x 2 columns]


In [47]:
# Q7.3 Select the first 7 values
df_Q7_3 = df_Q7_2.head(7)
print(f"VERIFICATION: \r\n{df_Q7_3}")

VERIFICATION: 
   vehicle_weight  model_year
0            3870        2006
1            4210        2008
2            4240        1996
3            4490        1989
4            4510        1994
5            4260        2007
6            4310        1992


In [48]:
# Q7.4 Get the underlying NumPy array. Let's call it X.
#import numpy as np
X = df_Q7_3.to_numpy()
print(f"VERIFICATION: \r\n{X}")

VERIFICATION: 
[[3870 2006]
 [4210 2008]
 [4240 1996]
 [4490 1989]
 [4510 1994]
 [4260 2007]
 [4310 1992]]


In [49]:
# Q7.5 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
import numpy as np

print(f"INFO: dimensions of matrix X: \r\n {X.shape} \r\n")
print(f"INFO: dimensions of matrix the transposed matrix X: \r\n {X.T.shape} \r\n")

XTX = np.dot(X,X.T)

print(f"ANSWER: dot product of X and XTX: \r\n {XTX}")

INFO: dimensions of matrix X: 
 (7, 2) 

INFO: dimensions of matrix the transposed matrix X: 
 (2, 7) 

ANSWER: dot product of X and XTX: 
 [[19000936 20320748 20412776 21366234 21453664 20512242 20675652]
 [20320748 21756164 21858368 22896812 22991052 21964656 22145036]
 [20412776 21858368 21961616 23007644 23102424 22068372 22250432]
 [21366234 22896812 23007644 24116221 24215966 23119323 23313988]
 [21453664 22991052 23102424 24215966 24316136 23214558 23410148]
 [20512242 21964656 22068372 23119323 23214558 22175649 22358544]
 [20675652 22145036 22250432 23313988 23410148 22358544 22544164]]


In [50]:
# Q7.6 Invert XTX.
#   1. invoke the inv (inverse) method in the
#   2. linear algebra namespace in the
#   3. numpy package

df_Q7_6 = np.linalg.inv(XTX)

print(f"ANSWER: \r\n  Inverse of XTX:\r\n {df_Q7_6}")

ANSWER: 
  Inverse of XTX:
 [[-2.49755468e+07 -5.15931115e+06 -5.75008413e+07  4.92523129e+07
  -1.30426237e+08  7.60759538e+06  1.61682302e+08]
 [ 2.94764665e+07  7.29310033e+06  5.47699096e+07 -3.18173445e+08
   3.97638087e+08 -8.26843307e+06 -1.63927558e+08]
 [-5.47977361e+07  2.68435456e+08  0.00000000e+00  0.00000000e+00
   5.29735664e+07  0.00000000e+00 -2.68435456e+08]
 [ 1.71580921e+08  2.68435456e+08 -2.68435456e+08 -2.68435456e+08
   6.31885134e+08 -2.68435456e+08 -2.68435456e+08]
 [-2.50234116e+08 -2.68435456e+08  2.68435456e+08  2.68435456e+08
  -8.20924812e+08  2.68435456e+08  5.36870912e+08]
 [-5.91583897e+07 -2.68435456e+08  2.68435456e+08  2.68435456e+08
  -4.74798694e+08 -0.00000000e+00  2.68435456e+08]
 [ 1.89112323e+08 -0.00000000e+00 -2.68435456e+08 -0.00000000e+00
   3.46620501e+08 -0.00000000e+00 -2.68435456e+08]]


In [51]:
# Q7.7 Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

# native python array
arr_py = [1100, 1300, 800, 900, 1000, 1100, 1200]
# preview python array
print(f"ANSWER: \r\n  native python array:\r\n {arr_py} \r\n")

# numpy array
arr_np = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# assign the array to the variable y
y = arr_np

# preview numpy array
print(f"ANSWER: \r\n  numpy array: \r\n {arr_np}")

ANSWER: 
  native python array:
 [1100, 1300, 800, 900, 1000, 1100, 1200] 

ANSWER: 
  numpy array: 
 [1100 1300  800  900 1000 1100 1200]


In [52]:
# Q7.8 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
ZZ = np.dot(df_Q7_6,XTX)

w = np.dot(ZZ,y)

print(f"ANSWER: \r\n  dot product of the Inverse of XTX multiplied by the transpose of X, and then this result is dot multiplied by y \r\n {w}")

ANSWER: 
  dot product of the Inverse of XTX multiplied by the transpose of X, and then this result is dot multiplied by y 
 [-49011.5780592   17354.94037867  28200.              0.
  -4400.          -4200.           1100.        ]


In [53]:
# Q7.9 What's the sum of all the elements of the result?

print(f"ANSWER: \r\n  Sum of all values in the vector returned in Q7.8:  {np.sum(w)}")

ANSWER: 
  Sum of all values in the vector returned in Q7.8:  -10956.637680530548
